_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/yolov2_reader.yml',
  '_base_/yolov2.yml',
]

snapshot_epoch: 1
weights: output/best_model

epoch: 400

LearningRate:
  base_lr: 0.002
  schedulers:
  - !PiecewiseDecay
    gamma: [1]
    milestones:
    - 270
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
