_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/yolov2_reader.yml',
  '_base_/yolov2.yml',
]

snapshot_epoch: 1
weights: output/yolov2_voc/best_model

epoch: 365

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 155
    - 232
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.7
    type: Momentum
  regularizer:
    factor: 0.00001
    type: L2
