architecture: YOLOv2
pretrain_weights: output/pretrained.pdparams
norm_type: sync_bn

YOLOv2:
  backbone: DarkNet19
  neck: YOLOv2Neck
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

YOLOv3Head:
  anchors: [[42, 55], [102, 128], [162, 259], [303, 155], [360, 320]]
  anchor_masks: [[0, 1, 2, 3, 4]]
  loss: YOLOv3Loss

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32]
  label_smooth: false

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.0001
    downsample_ratio: 32
    clip_bbox: true
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.0001
    nms_threshold: 0.5
    nms_top_k: 1000
